server:
  port: 8082

spring:
  application:
    name: notification
  datasource:
    url: jdbc:postgresql://localhost:5432/notification
    username: 'admin'
    password: 'admin'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true

service:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    registry-with-eureka: true